### ISSUE TITLE
ParseTextString - issue reading it

### ISSUE THREAD

**Issue by KeithETruesdell** [sirikothe/gotextfsm#5]
I am trying to use theis ibrary while getting some info from an AP via SSH.  
I am running a few simple commands on a Cisco device like `show run` and `show version`.  I am logged in properly, and "enabled login".  
I am able to send data and to read data.  
I cant seem to get the data into the dictionary and sometimes I get an error while parsing the data that the token is too long.

I separated the code out that is giving me problems, but I also setup a full example of everything from start to finish to test.  Below is just a snippet, but please forgive some of the stuff in it (like the `if err != nil` just printing the error or using the `time.Sleep()` function).  I had to take the pieces out of the project and cobble them together to make this simple example and in doing so i had to simplify some other functionality.  

```go
    /////////////////////////////
	// working up until here...this is where the textfsm / gotextfsm comes in
	/////////////////////////////

	_, err = inBuf.Write([]byte("show version\n"))
	if err != nil {
		fmt.Printf("Error writing: %v\n", err)
	}

	time.Sleep(5 * time.Second)

	// last output of reading the buffer
	_, err = outBuf.Read(b)
	if err != nil {
		fmt.Printf("Error reading: %v\n", err)
	}

	tmplByteArr, err := os.ReadFile("templates/cisco_ios_show_version.textfsm")

	fsm := gotextfsm.TextFSM{}
	err = fsm.ParseString(string(tmplByteArr))
	if err != nil {
		fmt.Printf("Error Parsing FSM Definitions: %v\n", err)
	}

	time.Sleep(5 * time.Second)

	parser := gotextfsm.ParserOutput{}
	err = parser.ParseTextString(string(b), fsm, true)
	if err != nil {
		fmt.Printf("Error Parsing buffer output: %v\n", err)
	}

	fmt.Printf("dict: %v\n", parser.Dict)

	///////////////////////
```

The error that I am getting is usually something like...
```
Error Parsing buffer output: 68 Line: Scanner Error bufio.Scanner: token too long
```

68 line is about the buffer output that was read.  I know there is a max buffer size.  Looking up the error specifically, I am not getting anything too specific.  Looking in the issues for the git repo, i am not seeing anything (besides what i posted).  The content of `show version` isn't that long (so I think) and I could post it if need be (minus some internal sensitive data.  
So I am doing something wrong with how the data is being read & fed here, but I don't know how or what exactly.
What am i doing wrong and how to correct things.

  [1]: https://github.com/sirikothe/gotextfsm

**Comment by sirikothe** [comment]
Hi. 
1. Can you please let me know what code is exactly in line 68? Which function call is that?
2. Can you paste the output of "show version" that you get from the device so that I can try that exact output to be parsed?
Thanks

**Comment by sirikothe** [comment]
Hi, Did you get a chance to provide the data?

**Comment by sirikothe** [comment]
Closing the issue. No information about the issue provided by the submitter.
